### ISSUE TITLE
Get IPAddress from transport

### ISSUE THREAD

**Issue by Wuushu** [rlotun/txWebSocket#1]
Is it possible to get this patched? It's just a minor "bonus" if it was possible. :)

**Comment by rlotun** [comment]
Made WebSocketTransport implement ITransport. Also added getPeer and getHost implementations that will allow you to get the IP of the connected client. Closed by c1178b04401b378f1b4bd7031c3c28a992d08fff

**Comment by Wuushu** [comment]
Super awesomeness, rlotun!
