### ISSUE TITLE
__init__ in simple_server.py example fired twice from one connection?

### ISSUE THREAD

**Issue by Wuushu** [rlotun/txWebSocket#2]
In the simple_server.py example, I added only print "**init**" under the **init** method.

class Testhandler(WebSocketHandler):
    def **init**(self, transport):
        WebSocketHandler.**init**(self, transport)
        self.periodic_call = task.LoopingCall(self.send_time)
        print "**init**", self, transport

On the client-side this is the only code being executed:

var ws = new WebSocket("ws://109.74.200.181:8090/test");
    ws.onopen = function()
    {
        alert('onopen fired!');
        //ws.send("message to send"); 
    };

(As you can see I changed the port in this example, but no other changes were made)

This causes output from ONE connection:

**init** <**main**.Testhandler object at 0x9e70a6c> <websocket.WebSocketTransport object at 0x9e7018c>
**init** <**main**.Testhandler object at 0x9e7062c> <websocket.WebSocketTransport object at 0x9e7018c>

I'm not good at this but it looks like there's two "selfs" or instances being made. And when the browser is being closed, connectionLost is only fired once. This has led to some strange behaviour in one of my applications. Users getting an increasing number of transports added to their "client", never getting cleaned out or "connectionLost".

Can you replicate this, or is it intended?

**Comment by Wuushu** [comment]
I added a print self, to the connectionLost method and this is what i get from 1 connection to the page:

**init** <**main**.Testhandler object at 0x8a484cc>
**init** <**main**.Testhandler object at 0x8a48b6c>
Lost connection:  <**main**.Testhandler object at 0x8a484cc>

It seems like it's the "first" connection getting it's connectionLost method fired. Not the second?

**Comment by Wuushu** [comment]
Anyone? Is this still being maintained?

**Comment by jeiting** [comment]
I confirmed the bug in the most recent Safari but it does not show up in Chrome.

**Comment by Wuushu** [comment]
Thank you jeiting, I have put using this library (unfortunately) on hold until this gets fixed. It's leading to excess memory useage and inconsistent behaviour when dealing with a pool of connections tied to a specific user. :( Hopefully rlotun will see this soon and know how to fix it. :)

**Comment by srounet** [comment]
Is this going to be fixed ?

**Comment by Wuushu** [comment]
Srounet, are you having the exact same problem as I?

**Comment by srounet** [comment]
Yes exactly the same, is it resolved for you ?

**Comment by bydooweedoo** [comment]
I have the same problem too.
It seems to only happen when draft76 is in use.

**Comment by rlotun** [comment]
Don't initialize the handler twice. Closed by edc670cb9aa0f38dc7c7b24b656ae240c261e380

**Comment by bydooweedoo** [comment]
Patch works. Thank you :) !
