### ISSUE TITLE
Handler Never Gets Deleted

### ISSUE THREAD

**Issue by teburd** [rlotun/txWebSocket#3]
**del** for my websockethandler never gets called, the object is never freed even when connections are lost

**Comment by Wuushu** [comment]
if in your program in the def connectionLost():

if you add a del self; does it help?

Bfrog, does your **init** method get called twice for each connection? (I added a debug-print statement and it prints twice: http://github.com/rlotun/txWebSocket/issues#issue/2)

**Comment by rlotun** [comment]
Fix some memory leaks.

We now explicity del references to objects as connections are dropped.
Also, there was a small bug in the example where the loopingCall had
to be `del`ed for the Handler object to be garbage collected.

Closed by ee31d15236ac6aa8ab6b36e897fb28cf6db48479
