### ISSUE TITLE
connectionMade implementation not available

### ISSUE THREAD

**Issue by tazzytazzy** [rlotun/txWebSocket#5]
Hello,
  Is there a way to get access to "connectionMade" so code can be ran when a socket is opened?  I'm new to twisted and tried to expose this function, but couldn't figure it out. Thanks.

**Comment by rlotun** [comment]
This is closed in https://github.com/rlotun/txWebSocket/commit/bdab65b7fa4e33fe691b11d4cca7984dbbeb6b08
